---
version: '3'
vars:
  FIRMWARE_ACTION_CONFIG_FILE: 'coreboot-linuxboot-example.json'

tasks:
  build-template:
    internal: true
    cmds:
      - firmware-action build --config='{{.CONFIG}}' --target='{{.TARGET}}' --recursive {{.CLI_ARGS}}
    requires:
      vars: [CONFIG, TARGET]

  #==================
  # coreboot example
  #==================

  build:coreboot-plain:
    desc: Build coreboot hello world example
    cmds:
      - task: build-template
        vars:
          CONFIG: coreboot-example.json
          TARGET: coreboot-example

  #=======================================
  # coreboot with Linux and uroot example
  #=======================================

  build:coreboot-linux:
    desc: Build coreboot hello world example
    cmds:
      - task: build-template
        vars:
          CONFIG: '{{.FIRMWARE_ACTION_CONFIG_FILE}}'
          TARGET: coreboot-example-with-linuxboot

  build:linux-with-uroot:
    desc: Build linux with uroot
    cmds:
      - task: build-template
        vars:
          CONFIG: '{{.FIRMWARE_ACTION_CONFIG_FILE}}'
          TARGET: linux-example-with-uroot

  build:uroot:
    desc: Build uroot
    cmds:
      - task: build-template
        vars:
          CONFIG: '{{.FIRMWARE_ACTION_CONFIG_FILE}}'
          TARGET: uroot-example

  #=============================================
  # Run coreboot with LinuxBoot example in QEMU
  #=============================================

  qemu:run-coreboot:
    desc: Run the coreboot in QEMU
    interactive: true
    cmds:
      - qemu-system-x86_64 -bios output-linuxboot-coreboot/coreboot.rom -serial stdio -M q35
