---
version: '3'
vars:
  FIRMWAREACTION_REPO: '.firmware-action'
  FIRMWAREACTION_VERSION: 'v0.2.0'

tasks:
  prepare-firmware-action-repo:
    desc: Task to clone firmware-action repository
    internal: true
    cmds:
      - if [ ! -d {{.FIRMWAREACTION_REPO}} ]; then
        git clone -b {{.FIRMWAREACTION_VERSION}} https://github.com/9elements/firmware-action.git {{.FIRMWAREACTION_REPO}};
        fi
      - cd {{.FIRMWAREACTION_REPO}}; git checkout {{.FIRMWAREACTION_VERSION}}

  build-firmware-action-binary:
    desc: Task to build a firmware-action binary
    internal: true
    deps: [prepare-firmware-action-repo]
    dir: ./{{.FIRMWAREACTION_REPO}}/action
    cmds:
      - if [ ! -f ../../firmware-action-{{.FIRMWAREACTION_VERSION}} ]; then
        GOARCH=amd64 go build -ldflags="-s -w" -o ../../firmware-action-{{.FIRMWAREACTION_VERSION}};
        fi
    env:
      CGO_ENABLED: 0

  build:
    desc: Template task to build a go binary
    deps: [build-firmware-action-binary]
    cmds:
      - ./firmware-action-v0.2.0 build --config=firmware-action.json --target=coreboot-example
