---
name: coreboot build
on:
  push:

permissions:
  contents: read

jobs:
  # Example of building coreboot
  build-coreboot-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: firmware-action
        uses: 9elements/firmware-action@v0.15.0
        with:
          config: 'coreboot-example.json'
          target: 'coreboot-example'
          recursive: 'false'
          debug: 'true'
          auto-cache: 'true'
          auto-artifact-download: 'true'
          auto-artifact-upload: 'true'
