---
name: coreboot build
on:
  push:

permissions:
  contents: read

jobs:
  # Example of building coreboot
  build-coreboot-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: firmware-action
        uses: 9elements/firmware-action@v0.14.1
        with:
          config: 'coreboot-example.json'
          target: 'coreboot-example'
          recursive: 'false'

      - name: Get artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coreboot-4.19
          path: output-coreboot-example
          retention-days: 30
